### ISSUE TITLE
add option to include/exclude metrics in comment

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/css-diff-action#6]
All projects are different and sometimes I'm not interested in complexity-related metrics, and sometimes I'm not interested in the amount of colors. I'd like an option to specifify which metrics to include or exclude.

## Example config with excluding
_This would create a table with ALL metrics, *except* the ones listed in the `exclude` array._

```yaml
- name: Project Wallace Diff
  uses: projectwallace/css-diff-action@master
  with:
    project-wallace-token: ${{ secrets.PROJECT_WALLACE_TOKEN }}
    github-token: ${{ secrets.GITHUB_TOKEN }}
    css-path: ./build/style.css
    exclude:
      - 'atrules.fontfaces.unique'
      - 'stylesheets.browserhacks.total'
```

## Example config with inclusion
_This would create a table with ONLY the metrics listed in the `include` array._

```yaml
- name: Project Wallace Diff
  uses: projectwallace/css-diff-action@master
  with:
    project-wallace-token: ${{ secrets.PROJECT_WALLACE_TOKEN }}
    github-token: ${{ secrets.GITHUB_TOKEN }}
    css-path: ./build/style.css
    include:
      - 'atrules.fontfaces.unique'
      - 'stylesheets.browserhacks.total'
```

## Additional

* Unknown options should be ignored
* It would be nice to support configs like `*.browserhacks` or `values.colors.*`
